### ISSUE TITLE
Make it so that having none of a flower in a bouquet would delete the flowers instead of having 0x that flower

### ISSUE THREAD

**Issue by samuelory** [AY2324S2-CS2113-T11-3/tp#103]

**Comment by JeffinsonDarmawan** [comment]
<img width="483" alt="image" src="https://github.com/AY2324S2-CS2113-T11-3/tp/assets/110618615/84e82ed5-e6ff-4f97-a8a1-c549f25e5de2">
The problem should be fixed already!

**Comment by JeffinsonDarmawan** [comment]
<img width="407" alt="image" src="https://github.com/AY2324S2-CS2113-T11-3/tp/assets/110618615/1ed34b9e-2836-4962-b8ad-aeaf2364c6b6">
Though in this case, the total price is still shown
