### ISSUE TITLE
[PE-D][Tester D] InvalidPathException not caught for save function

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T11-3/tp#127]
![image.png](https://raw.githubusercontent.com/fungg0/ped/main/files/9ea00ee4-9f20-402a-8eed-895995fff720.png)

If i name my bouquet with trailing "/", i cannot save them :(

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: fungg0/ped#9

**Comment by JeffinsonDarmawan** [comment]
<img width="842" alt="image" src="https://github.com/AY2324S2-CS2113-T11-3/tp/assets/110618615/fd9f2786-d180-44cd-ae49-99bad6df35b2">

I am unable to reproduce the error.
