### ISSUE TITLE
[PE-D][Tester C] Cannot choose which bouquet to delete if same name

### ISSUE THREAD

**Issue by nus-se-script** [AY2324S2-CS2113-T11-3/tp#131]
Deleting a bouquet which shares the same name as other bouquets automatically deletes the one that appears first in the list

![image.png](https://raw.githubusercontent.com/cyhjason29/ped/main/files/3b54e4d6-b6a4-4e28-a9f9-7c247187cca7.png)

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cyhjason29/ped#7

**Comment by IanFH** [comment]
Similar issue as adding flower to same bouquet. Same bouquet should not exists, will check recommended bouquet creation and make another issue
