### ISSUE TITLE
[PE-D][Tester D] NullPointerException not caught for recommend command

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T11-3/tp#135]
![image.png](https://raw.githubusercontent.com/fungg0/ped/main/files/2c5c3555-6115-4f73-aff9-6be9288630b5.png)

![image.png](https://raw.githubusercontent.com/fungg0/ped/main/files/e2d95bf8-b723-48e8-b41b-f579d1798644.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: fungg0/ped#12

**Comment by IanFH** [comment]
This means info command has null pointer exception. Recommend command goes back to the very beginning step if wrong input is detected
