### ISSUE TITLE
[PE-D][Tester C] Cannot remove flower from recommended bouquets

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T11-3/tp#137]
![image.png](https://raw.githubusercontent.com/cyhjason29/ped/main/files/788f62cc-6621-4bca-8bc1-4e8aeab7ad57.png)

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: cyhjason29/ped#10

**Comment by JeffinsonDarmawan** [comment]
Note: The problem only persist when creating the bouquet and removing the rose during the same run. 

If after the creating of the bouquet we exit the programme and we run the programme and remove the flowers, Rose is detected inside the bouquet can remove Rose works fine.
