### ISSUE TITLE
[PE-D][Tester C] Mismatching exit commands

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T11-3/tp#139]
![image.png](https://raw.githubusercontent.com/cyhjason29/ped/main/files/7f9b1ef4-524f-464e-89a9-41766c4f6605.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: cyhjason29/ped#12

**Comment by JeffinsonDarmawan** [comment]
Problem has been fixed in an earlier issue!
