### ISSUE TITLE
[PE-D][Tester B] Bug for description of parameter

### ISSUE THREAD

**Issue by nus-pe-script** [AY2324S2-CS2113-T11-3/tp#146]
Documentation Bug (Severity LOW)
 
Stating quantity must be a valid number might be too vague.

![image.png](https://raw.githubusercontent.com/NgYaoDong/ped/main/files/7a9dae5d-44f0-46f2-8f0c-e20ee90c49ad.png)

-------------
Labels: `severity.Low` `type.DocumentationBug`
original: NgYaoDong/ped#9

**Comment by JeffinsonDarmawan** [comment]
<img width="410" alt="image" src="https://github.com/AY2324S2-CS2113-T11-3/tp/assets/110618615/1cb04e2e-e06a-4560-b361-0807248db13d">

Changed "Quantity must be more than 0 and a valid number" into "Quantity must be between 1 and the current amount of flowers in the bouquet (inclusive)."
