### ISSUE TITLE
DG Review for T11-3

### ISSUE THREAD

**Issue by aditichadha1310** [AY2324S2-CS2113-T11-3/tp#151]
![image](https://github.com/AY2324S2-CS2113-T11-3/tp/assets/70324480/6da55bbd-1f4b-4db0-a0b3-347f6a2bdb95)

You can consider closing the activation bar of Florizz after the final return to the user and standardize the convention in all diagrams.
You can close the activation bar as in the diagram shown below-

![image](https://github.com/AY2324S2-CS2113-T11-3/tp/assets/70324480/7eb6feb7-10c4-43b9-a8c1-e1c31db48831)

**Comment by IanFH** [comment]
Noted with thanks!
