### ISSUE TITLE
Add and Remove do not correctly recognise flowers with a space in their name

### ISSUE THREAD

**Issue by samuelory** [AY2324S2-CS2113-T11-3/tp#160]
![image](https://github.com/AY2324S2-CS2113-T11-3/tp/assets/14734371/909b39ba-dbc4-4d79-9b2b-422802705ed0)

**Comment by JeffinsonDarmawan** [comment]
<img width="593" alt="image" src="https://github.com/AY2324S2-CS2113-T11-3/tp/assets/110618615/c1eb1309-e2e2-4100-9fc3-c817321f2ace">
Bug fixed
