### ISSUE TITLE
Code review for @IanFH  

### ISSUE THREAD

**Issue by aditichadha1310** [AY2324S2-CS2113-T11-3/tp#57]
![image](https://github.com/AY2324S2-CS2113-T11-3/tp/assets/70324480/5c0f66eb-714a-4bd8-b568-5ee07e4c64e5)
Good usage of assert commands.

![image](https://github.com/AY2324S2-CS2113-T11-3/tp/assets/70324480/3a06e736-ffab-4a93-be5d-c6b8a40eb357)
Avoid usage of magic numbers

**Comment by IanFH** [comment]
Noted with thanks 👍
