### ISSUE TITLE
Code review for @Ijaaz01 

### ISSUE THREAD

**Issue by aditichadha1310** [AY2324S2-CS2113-T11-3/tp#59]
![image](https://github.com/AY2324S2-CS2113-T11-3/tp/assets/70324480/27bef686-8dc8-48fd-a0f6-15ec5304c0f3)
Can I ask why are the assertions disabled?

**Comment by Ijaaz01** [comment]
Hi Aditi, I must have forgotten to re-enable them while I was testing out how to use assertions thank you for pointing it out!
