### ISSUE TITLE
Code review for @samuelory 

### ISSUE THREAD

**Issue by aditichadha1310** [AY2324S2-CS2113-T11-3/tp#60]
![image](https://github.com/AY2324S2-CS2113-T11-3/tp/assets/70324480/9fe8b22c-c2db-4423-acd6-eb07e8bd9a09)

You might want to store the logo in a final variable as it does not change through the course of this program

**Comment by samuelory** [comment]
I did that and i got a warning from intellij to put it as a local variable :/
